import type { Brand, Product, GalleryItem } from "@shared/schema";

// Sample data for development
export const sampleBrands: Brand[] = [
  {
    id: "1",
    nameAr: "ماركة الأناقة",
    nameEn: "Elegance Brand",
    slug: "marca-elegance",
    descriptionAr: "رائدة في الأناقة الرجالية",
    descriptionEn: "Leader in men's elegance",
    logoUrl: "/images/brands/marca-elegance.png",
    createdAt: new Date(),
  },
  {
    id: "2",
    nameAr: "دار الفخامة",
    nameEn: "Luxury House",
    slug: "dar-luxury",
    descriptionAr: "تصاميم فاخرة ومميزة",
    descriptionEn: "Luxurious and distinctive designs",
    logoUrl: "/images/brands/dar-luxury.png",
    createdAt: new Date(),
  },
  {
    id: "3",
    nameAr: "بيت الأزياء",
    nameEn: "Fashion House",
    slug: "bait-fashion",
    descriptionAr: "أزياء تقليدية عصرية",
    descriptionEn: "Modern traditional fashion",
    logoUrl: "/images/brands/bait-fashion.png",
    createdAt: new Date(),
  },
];

export const sampleProducts: Product[] = [
  {
    id: "1",
    nameAr: "ثوب ملكي فاخر",
    nameEn: "Royal Luxury Thobe",
    slug: "royal-luxury-thobe",
    descriptionAr: "ثوب تقليدي بتصميم ملكي فاخر مصنوع من أجود الأقمشة",
    descriptionEn: "Traditional thobe with royal luxury design made from finest fabrics",
    luxuryTaglineAr: "للملوك والأمراء",
    luxuryTaglineEn: "For Kings and Princes",
    price: "2500.00",
    salePrice: null,
    mainImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    images: [],
    brandId: "1",
    category: "ثياب",
    subcategory: "ثوب",
    tags: ["ثوب", "فاخر"],
    sizes: ["S", "M", "L", "XL"],
    colors: [],
    materialAr: "قطن فاخر",
    materialEn: "Premium Cotton",
    featured: true,
    isNew: false,
    isCustomizable: true,
    stock: 10,
    sku: "RT-001",
    metaTitle: "ثوب ملكي فاخر - الصقر الخليجي",
    metaDescription: "ثوب تقليدي بتصميم ملكي فاخر مصنوع من أجود الأقمشة",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    nameAr: "مشلح تراثي أصيل",
    nameEn: "Authentic Heritage Mishlah",
    slug: "authentic-heritage-mishlah",
    descriptionAr: "مشلح تقليدي يجمع بين الأصالة والعراقة",
    descriptionEn: "Traditional mishlah combining authenticity and heritage",
    luxuryTaglineAr: "تراث أصيل",
    luxuryTaglineEn: "Authentic Heritage",
    price: "3500.00",
    salePrice: null,
    mainImage: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    images: [],
    brandId: "2",
    category: "مشالح",
    subcategory: "مشلح",
    tags: ["مشلح", "تقليدي"],
    sizes: ["S", "M", "L", "XL"],
    colors: [],
    materialAr: "صوف فاخر",
    materialEn: "Premium Wool",
    featured: false,
    isNew: true,
    isCustomizable: true,
    stock: 5,
    sku: "AHM-001",
    metaTitle: "مشلح تراثي أصيل - الصقر الخليجي",
    metaDescription: "مشلح تقليدي يجمع بين الأصالة والعراقة",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    nameAr: "بشت ذهبي راقي",
    nameEn: "Elegant Golden Bisht",
    slug: "elegant-golden-bisht",
    descriptionAr: "بشت فاخر بتطريز ذهبي يليق بالمناسبات الخاصة",
    descriptionEn: "Luxurious bisht with golden embroidery perfect for special occasions",
    luxuryTaglineAr: "للمناسبات الخاصة",
    luxuryTaglineEn: "For Special Occasions",
    price: "4500.00",
    salePrice: null,
    mainImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    images: [],
    brandId: "3",
    category: "بشوت",
    subcategory: "بشت",
    tags: ["بشت", "فاخر"],
    sizes: ["S", "M", "L", "XL"],
    colors: [],
    materialAr: "حرير طبيعي",
    materialEn: "Natural Silk",
    featured: true,
    isNew: false,
    isCustomizable: true,
    stock: 3,
    sku: "EGB-001",
    metaTitle: "بشت ذهبي راقي - الصقر الخليجي",
    metaDescription: "بشت فاخر بتطريز ذهبي يليق بالمناسبات الخاصة",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleGalleryItems: GalleryItem[] = [
  {
    id: "1",
    title: "عرض أزياء تقليدية",
    description: "عرض مميز للأزياء التقليدية",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=1000",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "تفاصيل التطريز التقليدي",
    description: "تفاصيل دقيقة للتطريز اليدوي",
    imageUrl: "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "إكسسوارات تقليدية",
    description: "مجموعة من الإكسسوارات التراثية",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=1200",
    createdAt: new Date(),
  },
];
